"""empty message

Revision ID: ee8ae5d6c6c7
Revises: 
Create Date: 2021-08-27 00:19:34.257805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8ae5d6c6c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BOOK',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('publisher', sa.String(length=60), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rating'], ['BOOK_REVIEW.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BOOK_REVIEW',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=70), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('imagelink', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['BOOK.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['LIBRARY_USER.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LIBRARY_USER',
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('CHECK_OUT_BOOK',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('book_link', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=70), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['BOOK.id'], ),
    sa.ForeignKeyConstraint(['rating'], ['BOOK_REVIEW.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['LIBRARY_USER.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RESERVATION_BOOK',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=70), nullable=True),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('book_link', sa.String(length=255), nullable=True),
    sa.Column('book_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['BOOK.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['LIBRARY_USER.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TOTAL_CHECK_OUT_BOOK',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('book_link', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=70), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['BOOK.id'], ),
    sa.ForeignKeyConstraint(['rating'], ['BOOK_REVIEW.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['LIBRARY_USER.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TOTAL_CHECK_OUT_BOOK')
    op.drop_table('RESERVATION_BOOK')
    op.drop_table('CHECK_OUT_BOOK')
    op.drop_table('LIBRARY_USER')
    op.drop_table('BOOK_REVIEW')
    op.drop_table('BOOK')
    # ### end Alembic commands ###
